### ISSUE TITLE
deltapower-image fails to build with internal git.corp.linkedin.com references

### ISSUE THREAD

**Issue by truongmd** [linkedin/o19-bmc-firmware#1]
Testing the deltapower-image build, which fails on internal references to git.corp.linkedin.com repo's. Are there externally available u-boot references available for the code being consumed?

`meta-openbmc/meta-aspeed/recipes-bsp/u-boot/u-boot-fw-utils_2016.07.bb:SRC_URI = "git://git.corp.linkedin.com:29418/openbmc/uboot;branch=${SRCBRANCH};protocol=ssh \
meta-openbmc/meta-aspeed/recipes-bsp/u-boot/u-boot_2016.07.bb:SRC_URI = "git://git.corp.linkedin.com:29418/openbmc/uboot;branch=${SRCBRANCH};protocol=ssh \`

**Comment by sergiyzhuk** [comment]
should be no internal references here.
Dawid is checking.

**Comment by dfrycki** [comment]
fixed in 9e0ad0ddf00735591cea980313dccfae1e7a0b8f
